name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - uses: pnpm/action-setup@v3.0.0
      with:
        version: latest
    - name: Setup Nodejs
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 18
        cache: pnpm
    - name: Install packages and build
      run: |
        pnpm install --frozen-lockfile
        pnpm build
    - name: Deploy
      uses: crazy-max/ghaction-github-pages@v4.0.0
      with:
        target_branch: gh-pages
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
